export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_PWD = 'SET_PWD'
export const SET_ROLE = 'SET_ROLE'
export const SET_HOST = 'SET_HOST'
export const SET_STOMP = 'SET_STOMP'
